server:
  port: 8888
  env: LOCAL
spring:
  #profiles:
  #active: l11
  application:
    name: WorkService
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/work_hard_play_hard?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver: org.mariadb.jdbc.Driver
  redis:
    database: 15
    # Redis服务器地址
    host: 192.168.100.11
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 9Cpa7vy5nqup0A1s
    # 连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 1000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        # max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 10000
  cloud:
    nacos:
      discovery:
        server-addr: http://127.0.0.1:8848
        namespace: 47dea8bf-3dce-4c86-82bc-82f1497c57d2
      config:
        enabled: false
        server-addr: http://127.0.0.1:8848
        import-check: false
        namespace: 47dea8bf-3dce-4c86-82bc-82f1497c57d2
  autoconfigure:
    exclude: org.springframework.cloud.client.serviceregistry.AutoServiceRegistrationAutoConfiguration,org.springframework.cloud.client.serviceregistry.ServiceRegistryAutoConfiguration


#开放所有页面节点  默认只开启了health、info两个节点
management:
  endpoint:
    health:
      enabled: false
      show-details: always
    metrics:
      enabled: true
    loggers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: false



logging:
  level:
    root: INFO
    # sg.ctx.mpc.repository.**: debug
  config: classpath:logging-config.xml

xxl:
  job:
    accessToken: default_token
    admin:
      addresses: http://localhost:9000/xxl-job-admin
    executor:
      address: ''
      appname: worl-service
      ip: ''
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
      port: 9201






#ctx:
#  mpc:
#    proxy:
#      node-a:
#        url: http://127.0.0.1:9091
#      node-b:
#        url: http://127.0.0.1:9091
#      node-c:
#        url: http://127.0.0.1:9091
#      node-d:
#        url: http://127.0.0.1:9091
#      node-e:
#        url: http://127.0.0.1:9091
#    groups:
#      - id: 1
#        nodes: 3
#    system:
#      public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAm5W2L+Az7FL43+f8Vrksx8NJZb71IqeY47UNqB93kULZ/GgnL3rG0We6CDtUhJpSAcriPL51lxOnQnk4+scyV3lxS5wL4FbbfhOjFggDkyFQBguJ8JzC1M+hrdtLVfYHgFeZd2GImFSX4vlwsE9KDWR55WpY5uWSx8RZjNFVP1zFklbRUkzOgzuMSndXQ8IOZ1e3Wfv9A7h9CEsARhUipN12aQjYhciiAT/k2u8mRdxN3dIjD0lrrEk8UQWQw4ENQWSgMZLDkyAGmCLIxtPYmQRFvRuMSYF2DSmLMSnUTVv0dyqsA0NeMvLDhi28uNbcFfSThIHTIcDV7UhaNTUSMQIDAQAB
#    service:
#      etherscan-url: https://goerli.etherscan.io
#      gas-price-times: 1
#      btcscan-url: https://live.blockcypher.com/btc-testnet/

